name: CI - Backend

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/backend-ci.yml'
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/backend-ci.yml'
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format:check
      - name: Run lint
        run: npm run lint
      # - name: Test
      #   run: npm test
      - name: Build
        run: npm run build --if-present
